using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using P12Bridge.Core;

namespace P12Bridge.Infrastructure;

public sealed class LocalCertificateService : ILocalCertificateService
{
    private const int MinimumKeySizeBits = 2048;

    public PrivateKeyGenerationResult GeneratePrivateKey(int keySizeBits = MinimumKeySizeBits)
    {
        if (keySizeBits < MinimumKeySizeBits)
        {
            return PrivateKeyGenerationResult.Failure(new ValidationIssue(
                CertificateProofErrorCodes.InvalidKeySize,
                ValidationSeverity.Error,
                "Private key size is too small.",
                $"Use RSA {MinimumKeySizeBits} bits or larger."));
        }

        using var rsa = RSA.Create(keySizeBits);
        return PrivateKeyGenerationResult.Success(rsa.ExportPkcs8PrivateKey());
    }

    public CertificateGenerationResult GenerateCertificateSigningRequest(CertificateGenerationRequest request)
    {
        var subjectIssues = request.Subject.Validate();
        if (subjectIssues.Any(issue => issue.Severity == ValidationSeverity.Error))
        {
            return CertificateGenerationResult.Failure(subjectIssues.ToArray());
        }

        if (request.PrivateKeyPkcs8 is null || request.PrivateKeyPkcs8.Length == 0)
        {
            return CertificateGenerationResult.Failure(new ValidationIssue(
                CertificateProofErrorCodes.MissingPrivateKey,
                ValidationSeverity.Error,
                "Private key is required to generate a CSR.",
                "Generate or import a private key before creating the certificate request."));
        }

        try
        {
            using var rsa = RSA.Create();
            rsa.ImportPkcs8PrivateKey(request.PrivateKeyPkcs8, out _);

            var certificateRequest = new CertificateRequest(
                new X500DistinguishedName(request.Subject.ToDistinguishedName()),
                rsa,
                HashAlgorithmName.SHA256,
                RSASignaturePadding.Pkcs1);

            return CertificateGenerationResult.Success(certificateRequest.CreateSigningRequest());
        }
        catch (CryptographicException)
        {
            return CertificateGenerationResult.Failure(new ValidationIssue(
                CertificateProofErrorCodes.InvalidPrivateKey,
                ValidationSeverity.Error,
                "Private key data is invalid.",
                "Use a PKCS#8 RSA private key generated by P12Bridge or a compatible tool."));
        }
        catch (ArgumentException)
        {
            return CertificateGenerationResult.Failure(new ValidationIssue(
                CertificateProofErrorCodes.CsrGenerationFailed,
                ValidationSeverity.Error,
                "CSR generation failed because the certificate subject is invalid.",
                "Review the subject fields and remove unsupported characters."));
        }
    }

    public P12ExportResult ExportPkcs12(P12ExportRequest request)
    {
        if (request.CertificateDer is null || request.CertificateDer.Length == 0)
        {
            return P12ExportResult.Failure(new ValidationIssue(
                CertificateProofErrorCodes.MissingCertificate,
                ValidationSeverity.Error,
                "Certificate data is required to export a P12.",
                "Import the Apple-issued .cer file before exporting P12."));
        }

        if (request.PrivateKeyPkcs8 is null || request.PrivateKeyPkcs8.Length == 0)
        {
            return P12ExportResult.Failure(new ValidationIssue(
                CertificateProofErrorCodes.MissingPrivateKey,
                ValidationSeverity.Error,
                "Private key is required to export a P12.",
                "Restore the private key created with the CSR."));
        }

        if (string.IsNullOrWhiteSpace(request.Password))
        {
            return P12ExportResult.Failure(new ValidationIssue(
                CertificateProofErrorCodes.EmptyP12Password,
                ValidationSeverity.Error,
                "P12 password is required.",
                "Enter a password and store it safely; it is needed by build tools."));
        }

        try
        {
            using var certificate = new X509Certificate2(request.CertificateDer);
            using var rsa = RSA.Create();
            rsa.ImportPkcs8PrivateKey(request.PrivateKeyPkcs8, out _);
            using var certificateWithKey = certificate.CopyWithPrivateKey(rsa);

            return P12ExportResult.Success(certificateWithKey.Export(X509ContentType.Pkcs12, request.Password));
        }
        catch (CryptographicException)
        {
            return P12ExportResult.Failure(new ValidationIssue(
                CertificateProofErrorCodes.P12ExportFailed,
                ValidationSeverity.Error,
                "P12 export failed because the certificate or private key is invalid.",
                "Verify that the certificate was created from the matching CSR and private key."));
        }
    }
}
